### PR TITLE
[WIP] Add basic support for `PointSchedule` shrinking

### PR DESCRIPTION
**Pull request by Niols**
Obsolete. Extract information and close. Refer to https://github.com/IntersectMBO/ouroboros-consensus/pull/856 for new work on shrinking.

### CODE REVIEW

**Review by facundominguez — APPROVED** [review]
LGTM

**Comment by Niols** [comment]
Actually, I am second-guessing this approach so I wouldn't want to merge just yet. Hence the “do-not-merge” label. I have opened a spin-off PR for the commits improving printing; see here: https://github.com/input-output-hk/ouroboros-consensus/pull/822

**Comment by Niols** [comment]
Alright, I think it makes more sense now; WDYT?

**Comment by Niols** [comment]
Superseded by https://github.com/IntersectMBO/ouroboros-consensus/pull/881 apart from the notion of honest peer alertness. The commits are too old to be reused easily anyways.

**Pull request closed without merging**
